### ISSUE TITLE
Repository does not contain CoC

### ISSUE THREAD

**Issue by Zer0-One** [klvs/test#1]
I've recently noticed that this repository does not contain a code of conduct. In order to prevent confusion and possible problematic behavior, please consider adding one. You can view a rather large CoC [here](https://sqlite.org/codeofethics.html) if you need some inspiration.

**Comment by klvs** [comment]
Sir, this is a Wendy's.

This is a CoC-free repo. Please don't attempt to shove any CoC in it. Large or otherwise.
